name: env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - git
  - github3.py
  - hvplot
  - jupyter
  - lxml
  - matplotlib-base
  - networkx
  - pandas
  - pyvis
  - requests
  - xonsh
